// GENERATED BY scripts/render_harnesses.py — edit Olympus Core/adapter sources, not this output.
// Pure presentation logic; OpenCode's session store remains the source of truth.
type Session = { id: string; parentID?: string | null; agent?: string; title?: string }
type Row = { id: string; agent: string; title: string }

const names: Record<string, string> = {
  aegis: "Aegis — The Keeper",
  argus: "Argus — The Bug Hunter",
  atlas: "Atlas — The Planner",
  helios: "Helios — The Optimizer",
  kael: "Kael — The Master",
  kovan: "Kovan — The Coder",
  nox: "Nox — The Tester",
  orin: "Orin — The Architect",
  talos: "Talos — The Sentinel",
  thales: "Thales — The Sage",
  vera: "Vera — The Judge",
  veyra: "Veyra — The Explorer",
}

function label(agent?: string): string {
  const id = agent?.trim() || ""
  return names[id.toLowerCase()] ?? (id || "Subagent")
}

function title(session: Session): string {
  const value = (session.title || "").replace(/\s+/g, " ").trim()
  if (!value || /^(?:(?:new |child )?session|(?:subagent )?task|untitled)(?: \d+)?$/i.test(value)) {
    return session.agent?.toLowerCase() === "aegis" ? "Aegis task" : "Subagent task"
  }
  return value.length > 64 ? value.slice(0, 61) + "…" : value
}

export function activeChildren(
  currentID: string,
  sessions: readonly Session[],
  status: (id: string) => string,
): Row[] {
  const current = sessions.find((session) => session.id === currentID)
  if (!current || current.parentID != null) return []
  return sessions.filter((session) => session.parentID === currentID && status(session.id) === "running")
    .map((session) => ({ id: session.id, agent: label(session.agent), title: title(session) }))
}
