[CmdletBinding()]
param(
    [ValidateSet('opencode', 'codex', 'all')]
    [string]$Harness = 'opencode',
    [string]$SourceVersion = 'local',
    [string]$ProjectTarget = (Get-Location).Path,
    [switch]$VerifyOnly,
    [switch]$DryRun,
    [switch]$Uninstall
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$SourceRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$Utf8NoBom = [Text.UTF8Encoding]::new($false)
$ManifestRelative = 'olympus/orchestrator-install.json'
$script:ProjectOverrideDetected = $false

function Fail([string]$Code, [string]$Message) { throw "$Code`: $Message" }

function Normalize-Relative([string]$Path) {
    $value = $Path.Replace('\','/')
    if (-not $value -or [IO.Path]::IsPathRooted($value) -or $value -match '(^|/)\.\.(/|$)' -or $value -match '(^|/)\.(?:/|$)') {
        Fail 'GLOBAL_MANIFEST_INVALID' "Unsafe managed resource path: $Path"
    }
    return $value.TrimStart('/')
}

function Assert-SafeDestination([string]$Root, [string]$Relative) {
    $relative = Normalize-Relative $Relative
    $base = [IO.Path]::GetFullPath($Root).TrimEnd([char[]]@('\','/'))
    $full = [IO.Path]::GetFullPath((Join-Path $base ($relative -replace '/', [IO.Path]::DirectorySeparatorChar)))
    $prefix = $base + [IO.Path]::DirectorySeparatorChar
    if (-not $full.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
        Fail 'GLOBAL_PATH_UNSAFE' "Managed destination escapes its configuration root: $Relative"
    }
    $cursor = $base
    foreach ($part in ($relative -split '/')) {
        $cursor = Join-Path $cursor $part
        $item = Get-Item -LiteralPath $cursor -Force -ErrorAction SilentlyContinue
        if ($null -ne $item -and ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
            Fail 'GLOBAL_PATH_UNSAFE' "Managed destination traverses a reparse point: $Relative"
        }
    }
    return $full
}

function Get-TextHash([string]$Text) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try { ([BitConverter]::ToString($sha.ComputeHash($Utf8NoBom.GetBytes($Text)))).Replace('-', '').ToLowerInvariant() }
    finally { $sha.Dispose() }
}

function Get-FileHashText([string]$Path) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try { ([BitConverter]::ToString($sha.ComputeHash([IO.File]::ReadAllBytes($Path)))).Replace('-', '').ToLowerInvariant() }
    finally { $sha.Dispose() }
}

function Get-OpenCodeRoot {
    if ($env:OPENCODE_CONFIG_DIR) {
        return [IO.Path]::GetFullPath($env:OPENCODE_CONFIG_DIR)
    }
    $opencodeCommands = @(Get-Command opencode -CommandType Application -ErrorAction SilentlyContinue)
    if ($opencodeCommands.Count -eq 0) { Fail 'OPENCODE_UNAVAILABLE' 'OpenCode CLI is required to resolve its current global configuration directory.' }
    $opencode = $opencodeCommands[0]
    $oldLocation = (Get-Location).Path
    try {
        $probeLocation = [IO.Path]::GetFullPath([IO.Path]::GetTempPath())
        Set-Location -LiteralPath $probeLocation
        $lines = @(& $opencode.Source debug paths 2>&1)
        $exitCode = $LASTEXITCODE
    } finally { Set-Location -LiteralPath $oldLocation }
    if ($exitCode -ne 0) { Fail 'OPENCODE_PATH_DISCOVERY_FAILED' 'opencode debug paths failed outside the project target.' }
    $matches = @($lines | ForEach-Object {
        $match = [regex]::Match([string]$_, '^\s*config\s{2,}(?<path>.+?)\s*$')
        if ($match.Success) { $match.Groups['path'].Value.Trim() }
    } | Where-Object { $_ })
    if ($matches.Count -ne 1 -or -not [IO.Path]::IsPathFullyQualified($matches[0])) {
        Fail 'OPENCODE_PATH_DISCOVERY_FAILED' 'Current OpenCode CLI did not provide exactly one absolute global config path.'
    }
    return [IO.Path]::GetFullPath($matches[0])
}

function Get-CodexRoot {
    $root = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path ([Environment]::GetFolderPath([Environment+SpecialFolder]::UserProfile)) '.codex' }
    if (-not [IO.Path]::IsPathFullyQualified($root)) { Fail 'CODEX_PATH_INVALID' 'CODEX_HOME must be an absolute path.' }
    return [IO.Path]::GetFullPath($root)
}

function Add-GeneratedOutput([System.Collections.IDictionary]$Outputs, [string]$Relative, [string]$SourcePath) {
    if (-not (Test-Path -LiteralPath $SourcePath -PathType Leaf)) { Fail 'SOURCE_FILE_MISSING' "Generated global resource is missing: $SourcePath" }
    $text = [IO.File]::ReadAllText($SourcePath)
    if ($text -notmatch 'GENERATED BY scripts/render_harnesses\.py') { Fail 'SOURCE_INVALID' "Not a generated Harness Core output: $SourcePath" }
    $Outputs[$Relative] = $text
}

function Get-GlobalOutputs([string]$SelectedHarness) {
    $outputs = [ordered]@{}
    if ($SelectedHarness -eq 'opencode') {
        $agentRoot = Join-Path $SourceRoot '.opencode/agents'
        foreach ($file in @(Get-ChildItem -LiteralPath $agentRoot -Filter '*.md' -File | Sort-Object Name)) {
            Add-GeneratedOutput $outputs ('agents/' + $file.Name) $file.FullName
        }
        Add-GeneratedOutput $outputs 'commands/maintain.md' (Join-Path $SourceRoot '.opencode/commands/maintain.md')
        $pluginRoot = Join-Path $SourceRoot '.opencode/plugins/olympus-activity'
        foreach ($file in @(Get-ChildItem -LiteralPath $pluginRoot -File -Recurse | Sort-Object FullName)) {
            $relative = $file.FullName.Substring($pluginRoot.Length + 1).Replace('\','/')
            Add-GeneratedOutput $outputs ('plugins/olympus-activity/' + $relative) $file.FullName
        }
        if ($outputs.Count -ne 15) { Fail 'SOURCE_INVALID' "Unexpected OpenCode global resource inventory: $($outputs.Count)." }
    } else {
        $agentRoot = Join-Path $SourceRoot '.codex/agents'
        foreach ($file in @(Get-ChildItem -LiteralPath $agentRoot -Filter '*.toml' -File | Sort-Object Name)) {
            Add-GeneratedOutput $outputs ('agents/' + $file.Name) $file.FullName
        }
        $profile = Join-Path $SourceRoot '.codex/config.toml'
        Add-GeneratedOutput $outputs 'olympus.config.toml' $profile
        $rootInstructions = Join-Path $SourceRoot 'CODEX.md'
        if (-not (Test-Path -LiteralPath $rootInstructions -PathType Leaf)) { Fail 'SOURCE_FILE_MISSING' 'Generated Codex root instructions are missing.' }
        $rootText = [IO.File]::ReadAllText($rootInstructions)
        if ($rootText -notmatch 'GENERATED BY scripts/render_harnesses\.py') { Fail 'SOURCE_INVALID' 'Codex root instructions are not generated Harness Core output.' }
        $newIntro = 'This is the global Olympus root instruction and Kael identity. Start Codex with `codex --profile olympus` to use the global Olympus model and agent defaults. Project-local instructions and overrides remain in place and take precedence where Codex defines them.'
        $rootText = [regex]::Replace($rootText, '(?s)This file is the Codex adapter''s root representation:.*?Codex owns the user-facing result\.', [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $newIntro }, 1)
        if ($rootText -notmatch 'codex --profile olympus') { Fail 'SOURCE_INVALID' 'Could not adapt Codex root instructions for global profile use.' }
        $outputs['AGENTS.md'] = $rootText
        if ($outputs.Count -ne 12) { Fail 'SOURCE_INVALID' "Unexpected Codex global resource inventory: $($outputs.Count)." }
    }
    return ,$outputs
}

function Read-GlobalManifest([string]$Root, [string]$Harness, [switch]$Required) {
    $path = Assert-SafeDestination $Root $ManifestRelative
    if (-not (Test-Path -LiteralPath $path)) {
        if ($Required) { Fail 'GLOBAL_MANIFEST_MISSING' "No Olympus global ownership manifest exists for $Harness." }
        return $null
    }
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { Fail 'GLOBAL_MANIFEST_CONFLICT' 'Global manifest path is not a file.' }
    try { $manifest = [IO.File]::ReadAllText($path) | ConvertFrom-Json -Depth 100 }
    catch { Fail 'GLOBAL_MANIFEST_INVALID' 'Global ownership manifest is invalid JSON.' }
    if ($manifest.schema_version -ne 1 -or $manifest.scope -cne 'global' -or @($manifest.installed_harnesses).Count -ne 1 -or
        [string]$manifest.installed_harnesses[0] -cne $Harness -or $null -eq $manifest.managed_files) {
        Fail 'GLOBAL_MANIFEST_INVALID' 'Global manifest scope, harness inventory, or schema is unsupported.'
    }
    $entries = @($manifest.managed_files)
    $seen = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    foreach ($entry in $entries) {
        $relative = Normalize-Relative ([string]$entry.path)
        if (-not $seen.Add($relative)) { Fail 'GLOBAL_MANIFEST_INVALID' "Duplicate global resource path: $relative" }
        $full = Assert-SafeDestination $Root $relative
        if (-not (Test-Path -LiteralPath $full -PathType Leaf)) { Fail 'GLOBAL_MANAGED_FILE_DRIFT' "Managed global file is missing: $relative" }
        if ((Get-FileHashText $full) -cne ([string]$entry.sha256).ToLowerInvariant()) {
            Fail 'GLOBAL_MANAGED_FILE_DRIFT' "Managed global file changed: $relative"
        }
    }
    return $manifest
}

function Get-ManifestEntryMap($Manifest) {
    $result = @{}
    if ($null -ne $Manifest) { foreach ($entry in @($Manifest.managed_files)) { $result[(Normalize-Relative ([string]$entry.path))] = $entry } }
    return $result
}

function Write-GlobalResource([string]$Path, [string]$Content) {
    $parent = Split-Path -Parent $Path
    [IO.Directory]::CreateDirectory($parent) | Out-Null
    [IO.File]::WriteAllText($Path, $Content, $Utf8NoBom)
}

function Get-ProjectOverride([string]$Harness, [string]$GlobalVersion) {
    $git = Get-Command git -CommandType Application -ErrorAction SilentlyContinue
    if (-not $git -or -not (Test-Path -LiteralPath $ProjectTarget -PathType Container)) { return }
    $projectRoot = (& $git.Source -C $ProjectTarget rev-parse --show-toplevel 2>$null | Out-String).Trim()
    if ($LASTEXITCODE -ne 0 -or -not $projectRoot) { return }
    $localManifestRel = if ($Harness -eq 'opencode') { '.opencode/orchestrator-install.json' } else { '.codex/orchestrator-install.json' }
    $manifestPath = Join-Path $projectRoot ($localManifestRel -replace '/', [IO.Path]::DirectorySeparatorChar)
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) { return }
    try {
        $local = [IO.File]::ReadAllText($manifestPath) | ConvertFrom-Json -Depth 100
        $harnesses = if ($local.installed_harnesses) { @($local.installed_harnesses) } else { @('opencode') }
        if ($Harness -notin $harnesses) { return }
        $script:ProjectOverrideDetected = $true
        $localVersion = [string]$local.installed_version
        $isDrifted = $false
        foreach ($entry in @($local.managed_files)) {
            $relative = Normalize-Relative ([string]$entry.path)
            $full = Join-Path $projectRoot ($relative -replace '/', [IO.Path]::DirectorySeparatorChar)
            if (-not (Test-Path -LiteralPath $full -PathType Leaf) -or (Get-FileHashText $full) -cne ([string]$entry.sha256).ToLowerInvariant()) { $isDrifted = $true; break }
        }
        $status = if ($isDrifted) { 'modified local resources; preserved' } elseif ($localVersion -cne $GlobalVersion) { "version $localVersion differs from global $GlobalVersion; preserved" } else { "version $localVersion remains a project-local override" }
        Write-Output "PROJECT_LOCAL_OVERRIDE: $Harness $status ($projectRoot)"
    } catch { Write-Output "PROJECT_LOCAL_OVERRIDE: $Harness manifest/path is invalid; preserved at $manifestPath" }
}

function Invoke-OneHarness([string]$SelectedHarness) {
    $script:ProjectOverrideDetected = $false
    $root = if ($SelectedHarness -eq 'opencode') { Get-OpenCodeRoot } else { Get-CodexRoot }
    if (-not [IO.Path]::IsPathFullyQualified($root)) { Fail 'GLOBAL_PATH_INVALID' 'Resolved global root is not absolute.' }
    $manifestPath = Assert-SafeDestination $root $ManifestRelative

    if ($Uninstall) {
        $manifest = Read-GlobalManifest $root $SelectedHarness -Required
        $entryMap = Get-ManifestEntryMap $manifest
        if ($DryRun) {
            Write-Output "GLOBAL_UNINSTALL_DRY_RUN: $SelectedHarness"
            foreach ($relative in @($entryMap.Keys | Sort-Object)) { Write-Output "REMOVE: $relative" }
            Write-Output "REMOVE: $ManifestRelative"
            return
        }
        foreach ($relative in @($entryMap.Keys | Sort-Object)) {
            $full = Assert-SafeDestination $root $relative
            [IO.File]::Delete($full)
        }
        [IO.File]::Delete($manifestPath)
        Write-Output "OLYMPUS_GLOBAL_UNINSTALL: $SelectedHarness REMOVED_MANAGED_RESOURCES_ONLY"
        return
    }

    $outputs = Get-GlobalOutputs $SelectedHarness
    if ($SelectedHarness -eq 'codex') {
        $higherPrecedenceInstructions = Assert-SafeDestination $root 'AGENTS.override.md'
        if (Test-Path -LiteralPath $higherPrecedenceInstructions) {
            Fail 'GLOBAL_INSTALL_CONFLICT' 'User-owned global AGENTS.override.md takes precedence over AGENTS.md; refusing an inactive Olympus global root.'
        }
    }
    $manifest = Read-GlobalManifest $root $SelectedHarness
    $oldEntries = Get-ManifestEntryMap $manifest
    $newEntries = @{}
    $create = [System.Collections.Generic.List[string]]::new()
    $update = [System.Collections.Generic.List[string]]::new()
    $remove = [System.Collections.Generic.List[string]]::new()

    foreach ($relative in @($outputs.Keys | Sort-Object)) {
        $full = Assert-SafeDestination $root $relative
        $newEntries[$relative] = [ordered]@{ path=$relative; sha256=Get-TextHash ([string]$outputs[$relative]) }
        if (-not (Test-Path -LiteralPath $full)) { $create.Add($relative); continue }
        if ($oldEntries.ContainsKey($relative)) {
            if ((Get-FileHashText $full) -cne ([string]$oldEntries[$relative].sha256).ToLowerInvariant()) {
                Fail 'GLOBAL_MANAGED_FILE_DRIFT' "Refusing to overwrite modified managed global resource: $relative"
            }
            if ((Get-FileHashText $full) -cne (Get-TextHash ([string]$outputs[$relative]))) { $update.Add($relative) }
        } elseif ((Get-FileHashText $full) -cne (Get-TextHash ([string]$outputs[$relative]))) {
            Fail 'GLOBAL_INSTALL_CONFLICT' "User-owned global destination differs from Olympus output: $relative"
        }
    }
    foreach ($relative in @($oldEntries.Keys)) { if (-not $newEntries.ContainsKey($relative)) { $remove.Add($relative) } }
    foreach ($relative in $remove) { [void](Assert-SafeDestination $root $relative) }

    if ($VerifyOnly) {
        if ($null -ne $manifest -and [string]$manifest.installed_version -cne $SourceVersion) {
            Fail 'GLOBAL_VERSION_DRIFT' "Global manifest records '$($manifest.installed_version)'; requested '$SourceVersion'."
        }
        if ($create.Count -or $update.Count -or $remove.Count) {
            Fail 'GLOBAL_MANAGED_FILE_DRIFT' "Global $SelectedHarness installation differs from the requested source (create=$($create.Count), update=$($update.Count), remove=$($remove.Count))."
        }
        Write-Output "OLYMPUS_GLOBAL_VERIFY: $SelectedHarness $SourceVersion PASS (read-only; $($outputs.Count) managed resources)"
        return
    }
    if ($DryRun) {
        Write-Output "GLOBAL_INSTALL_DRY_RUN: $SelectedHarness"
        foreach ($relative in $create) { Write-Output "CREATE: $relative" }
        foreach ($relative in $update) { Write-Output "UPDATE: $relative" }
        foreach ($relative in $remove) { Write-Output "REMOVE: $relative" }
        return
    }

    $commit = (& git -C $SourceRoot rev-parse HEAD 2>$null | Out-String).Trim()
    if ($LASTEXITCODE -ne 0 -or -not $commit) { $commit = 'unknown' }
    $fileEntries = foreach ($relative in @($newEntries.Keys | Sort-Object)) { $newEntries[$relative] }
    $manifestText = ([ordered]@{
        schema_version = 1
        scope = 'global'
        installed_harnesses = @($SelectedHarness)
        installed_version = $SourceVersion
        installed_from_commit = $commit
        managed_files = @($fileEntries)
    } | ConvertTo-Json -Depth 20) + "`n"
    $manifestHash = Get-TextHash $manifestText
    $manifestChanged = -not (Test-Path -LiteralPath $manifestPath) -or (Get-FileHashText $manifestPath) -cne $manifestHash
    foreach ($relative in $remove) { [IO.File]::Delete((Assert-SafeDestination $root $relative)) }
    foreach ($relative in @($outputs.Keys | Sort-Object)) {
        if ($relative -in $create -or $relative -in $update) {
            Write-GlobalResource (Assert-SafeDestination $root $relative) ([string]$outputs[$relative])
        }
    }
    if ($manifestChanged) { Write-GlobalResource $manifestPath $manifestText }
    Get-ProjectOverride $SelectedHarness $SourceVersion
    $status = if (-not ($create.Count -or $update.Count -or $remove.Count -or $manifestChanged)) { 'NO_CHANGES' } else { 'READY' }
    $rootLabel = if ($SelectedHarness -eq 'opencode') { 'OPENCODE' } else { 'CODEX' }
    Write-Output "OLYMPUS_GLOBAL_INSTALL: $rootLabel $SourceVersion $status ($($outputs.Count) managed resources; root=$root)"
    if ($script:ProjectOverrideDetected) { Write-Output 'OLYMPUS_GLOBAL_MIGRATION: GLOBAL_INSTALLED PROJECT_LOCAL_REMAINS_AS_OVERRIDE' }
    if ($SelectedHarness -eq 'opencode') {
        Write-Output 'GLOBAL_DEFAULT_AGENT: unchanged; select Kael explicitly to preserve user-owned global config.'
    } else {
        Write-Output 'GLOBAL_CODEX_PROFILE: codex --profile olympus; base config.toml is not modified.'
    }
}

try {
    if ([Environment]::OSVersion.Platform -ne [PlatformID]::Win32NT) { Fail 'PLATFORM_UNQUALIFIED' 'Global installation currently requires Windows; Unix path layouts are documented but not installer-qualified.' }
    if ($VerifyOnly -and $DryRun) { Fail 'VERIFY_MODE_INVALID' '-VerifyOnly and -DryRun cannot be combined.' }
    if ($VerifyOnly -and $Uninstall) { Fail 'VERIFY_MODE_INVALID' '-VerifyOnly and -Uninstall cannot be combined.' }
    $selected = if ($Harness -eq 'all') { @('opencode','codex') } else { @($Harness) }
    $failures = [System.Collections.Generic.List[string]]::new()
    foreach ($name in $selected) {
        try { Invoke-OneHarness $name }
        catch { $failures.Add("$name`: $($_.Exception.Message)"); Write-Output "GLOBAL_HARNESS_FAILED: $name $($_.Exception.Message)" }
    }
    if ($failures.Count) { throw ('GLOBAL_INSTALL_PARTIAL_OR_FAILED: ' + ($failures -join ' | ')) }
} catch {
    Write-Error $_.Exception.Message
    exit 1
}
