#!/usr/bin/env python3
"""Render the two supported Olympus runtime adapters from checked-in sources."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path


CAPABILITIES = (
    "ROOT_ORCHESTRATOR",
    "CUSTOM_SPECIALISTS",
    "PER_ROLE_MODEL",
    "PER_ROLE_REASONING",
    "MULTI_AGENT",
    "BOUNDED_PARALLELISM",
    "QUESTION_CENTRALIZATION",
    "COMPLETION_BARRIER",
    "RESULT_DELIVERY",
    "RESULT_RECONCILIATION",
    "ALLOW",
    "ASK",
    "DENY",
    "AEGIS",
    "ACTIVITY_VISIBILITY",
)
VALID_STATES = {"SUPPORTED", "ADAPTABLE", "PARTIAL", "GAP", "NOT_NEEDED"}
GENERATED = "GENERATED BY scripts/render_harnesses.py — edit Olympus Core/adapter sources, not this output."


class RenderError(Exception):
    pass


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise RenderError(f"cannot read {path}: {error}") from error


def read_toml(path: Path) -> dict:
    try:
        with path.open("rb") as stream:
            return tomllib.load(stream)
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise RenderError(f"cannot parse {path}: {error}") from error


def role_ids(root: Path) -> set[str]:
    roles = root / "olympus" / "roles"
    ids = {path.stem for path in roles.glob("*.md") if path.is_file()}
    if not ids:
        raise RenderError(f"no canonical roles found under {roles}")
    return ids


def checked_sources(root: Path) -> tuple[dict, dict, dict, dict[str, str], set[str]]:
    models = read_toml(root / "olympus" / "core" / "models.toml")
    identity_source = read_toml(root / "olympus" / "core" / "identities.toml")
    policies = read_toml(root / "olympus" / "policies" / "orchestration.toml")
    capabilities = read_toml(root / "olympus" / "harnesses" / "capabilities.toml")
    roles = role_ids(root)
    model_roles = set(models.get("roles", {}))
    if roles != model_roles:
        raise RenderError(
            "canonical role roster differs between olympus/roles and olympus/core/models.toml: "
            f"roles-only={sorted(roles - model_roles)}, models-only={sorted(model_roles - roles)}"
        )
    identities = {role: value.get("display", "").strip() for role, value in identity_source.get("roles", {}).items()}
    if set(identities) != roles or any(not display for display in identities.values()):
        raise RenderError(
            "canonical identity roster differs from canonical roles: "
            f"missing={sorted(roles - set(identities))}, unexpected={sorted(set(identities) - roles)}"
        )
    if len({display.casefold() for display in identities.values()}) != len(identities):
        raise RenderError("canonical display identities must be unique")
    for role, display in identities.items():
        if display.split(" — ", 1)[0].casefold() != role.casefold() or " — " not in display:
            raise RenderError(f"canonical display identity for {role!r} must preserve its technical ID")
    for family, info in models.get("families", {}).items():
        if not info.get("opencode") or not info.get("codex"):
            raise RenderError(f"model family {family!r} needs both OpenCode and Codex identifiers")
    for role, info in models["roles"].items():
        if info.get("family") not in models["families"] or not info.get("effort"):
            raise RenderError(f"incomplete canonical model intent for role {role!r}")
    if not isinstance(policies.get("max_children"), int) or policies["max_children"] < 1:
        raise RenderError("olympus/policies/orchestration.toml must define positive integer max_children")
    if set(capabilities) != {"opencode", "codex"}:
        raise RenderError("capability contract must declare exactly the OpenCode and Codex adapters")
    for harness, values in capabilities.items():
        if set(values) != set(CAPABILITIES):
            raise RenderError(
                f"{harness} capability IDs differ: missing={sorted(set(CAPABILITIES) - set(values))}, "
                f"unexpected={sorted(set(values) - set(CAPABILITIES))}"
            )
        invalid = {name: state for name, state in values.items() if state not in VALID_STATES}
        if invalid:
            raise RenderError(f"invalid {harness} capability state(s): {invalid}")
    return models, policies, capabilities, identities, roles


def role_model(models: dict, role: str, harness: str) -> tuple[str, str]:
    try:
        role_intent = models["roles"][role]
        family = models["families"][role_intent["family"]]
        model = family[harness]
        effort = role_intent["effort"]
    except KeyError as error:
        raise RenderError(f"missing {harness} model intent for {role}: {error}") from error
    return model, effort


def replace_tokens(text: str, values: dict[str, object], source: Path) -> str:
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", str(value))
    unresolved = sorted(set(re.findall(r"\{\{[A-Za-z0-9_]+\}\}", text)))
    if unresolved:
        raise RenderError(f"unresolved template token(s) in {source}: {', '.join(unresolved)}")
    return text


def markdown_section(text: str, heading: str, source: Path) -> str:
    lines = text.splitlines()
    try:
        start = next(index for index, line in enumerate(lines) if line.strip() == heading)
    except StopIteration as error:
        raise RenderError(f"missing {heading!r} in {source}") from error
    end = next((index for index in range(start + 1, len(lines)) if lines[index].startswith("#")), len(lines))
    return "\n".join(lines[start:end]).strip()


def add_yaml_comment(header: str, message: str) -> str:
    if not header.startswith("---\n") or not header.endswith("\n---\n"):
        raise RenderError("OpenCode agent metadata must be a YAML frontmatter block")
    return header.replace("---\n", f"---\n# {message}\n", 1)


def add_markdown_comment(text: str, message: str) -> str:
    text = text.removeprefix("\ufeff")
    if text.startswith("---"):
        frontmatter = re.match(r"\A---\n.*?^---[ \t]*(?:\n|$)", text, re.MULTILINE | re.DOTALL)
        if frontmatter is None:
            raise RenderError("Markdown YAML frontmatter must start with --- and close with ---")
        return text[: frontmatter.end()] + f"<!-- {message} -->\n" + text[frontmatter.end() :]
    return f"<!-- {message} -->\n" + text


def prefix_yaml_description(text: str, identity: str, source: Path) -> str:
    match = re.search(r"(?m)^description:[ \t]*(.*?)[ \t]*$", text)
    if match is None:
        raise RenderError(f"OpenCode metadata has no description field: {source}")
    try:
        description = json.loads(match.group(1)) if match.group(1).startswith('"') else match.group(1)
    except json.JSONDecodeError as error:
        raise RenderError(f"invalid OpenCode description in {source}: {error}") from error
    rendered = "description: " + json.dumps(f"{identity}. {description}", ensure_ascii=False)
    return text[: match.start()] + rendered + text[match.end() :]


def prefix_toml_description(text: str, identity: str, source: Path) -> str:
    match = re.search(r'(?m)^description[ \t]*=[ \t]*("(?:[^"\\]|\\.)*")[ \t]*$', text)
    if match is None:
        raise RenderError(f"Codex agent source has no supported description field: {source}")
    try:
        description = json.loads(match.group(1))
    except json.JSONDecodeError as error:
        raise RenderError(f"invalid Codex description in {source}: {error}") from error
    rendered = json.dumps(f"{identity}. {description}", ensure_ascii=False)
    return text[: match.start(1)] + rendered + text[match.end(1) :]


def opencode_outputs(root: Path, models: dict, policies: dict, identities: dict[str, str], roles: set[str]) -> dict[Path, str]:
    adapter = root / "olympus" / "harnesses" / "opencode"
    maintenance_policy_path = root / "olympus" / "policies" / "maintenance-plane.md"
    maintenance_policy = read_text(maintenance_policy_path).strip()
    maintenance_target_boundary = markdown_section(
        maintenance_policy,
        "## Target ownership and project-plane boundary",
        maintenance_policy_path,
    )
    metadata_dir = adapter / "agent-metadata"
    prompts_dir = adapter / "agent-prompts"
    metadata_roles = {path.stem for path in metadata_dir.glob("*.md") if path.is_file()}
    prompt_roles = {path.stem for path in prompts_dir.glob("*.md") if path.is_file()}
    if metadata_roles != roles or prompt_roles != roles:
        raise RenderError(
            "OpenCode adapter must have one metadata block and prompt for every canonical role; "
            f"metadata missing={sorted(roles - metadata_roles)}, prompts missing={sorted(roles - prompt_roles)}, "
            f"unexpected={sorted((metadata_roles | prompt_roles) - roles)}"
        )

    children = policies["max_children"]
    word = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight"}.get(children)
    if word is None:
        raise RenderError("max_children outside supported word mapping (1..8)")
    output: dict[Path, str] = {}
    for role in sorted(roles):
        metadata_path = metadata_dir / f"{role}.md"
        prompt_path = prompts_dir / f"{role}.md"
        model, effort = role_model(models, role, "opencode")
        values = {"opencode_model": model, "effort": effort}
        metadata = prefix_yaml_description(replace_tokens(read_text(metadata_path), values, metadata_path), identities[role], metadata_path)
        prompt = replace_tokens(
            read_text(prompt_path),
            {
                "max_children": children,
                "max_children_word": word,
                "max_children_title": word.title(),
                "display_identity": identities[role],
                "maintenance_plane_policy": maintenance_policy,
                "maintenance_target_boundary": maintenance_target_boundary,
            },
            prompt_path,
        )
        display = identities[role]
        header = add_yaml_comment(metadata, f"{GENERATED} Canonical Olympus role: olympus/roles/{role}.md ({display}).")
        output[root / ".opencode" / "agents" / f"{role}.md"] = header + prompt

    config_path = adapter / "config.jsonc"
    config = replace_tokens(
        read_text(config_path),
        {"opencode_kael_model": role_model(models, "kael", "opencode")[0]},
        config_path,
    )
    output[root / "opencode.jsonc"] = config.replace("{\n", f"{{\n  // {GENERATED}\n", 1)

    display_names = "\n".join(f'  {role}: {json.dumps(identities[role], ensure_ascii=False)},' for role in sorted(roles))
    for source_name, output_path, comment in (
        ("maintain.md", root / ".opencode" / "commands" / "maintain.md", f"<!-- {GENERATED} -->\n"),
        ("activity.ts", root / ".opencode" / "plugins" / "olympus-activity" / "activity.ts", f"// {GENERATED}\n"),
        ("tui.tsx", root / ".opencode" / "plugins" / "olympus-activity" / "tui.tsx", f"// {GENERATED}\n"),
    ):
        source_path = adapter / source_name
        body = read_text(source_path)
        if source_name == "maintain.md":
            body = replace_tokens(body, {"maintenance_plane_policy": maintenance_policy, "display_identity": identities["aegis"]}, source_path)
        elif source_name == "activity.ts":
            body = replace_tokens(body, {"display_names": display_names}, source_path)
        output[output_path] = add_markdown_comment(body, GENERATED) if source_name.endswith(".md") else comment + body
    return output


def codex_outputs(root: Path, models: dict, policies: dict, identities: dict[str, str], roles: set[str]) -> dict[Path, str]:
    adapter = root / "olympus" / "harnesses" / "codex"
    agents_dir = adapter / "agents"
    expected = roles - {"kael", "aegis"}
    actual = {path.stem for path in agents_dir.glob("*.toml") if path.is_file()}
    if actual != expected:
        raise RenderError(
            "Codex custom-agent adapter must contain exactly the supported specialist roles; "
            f"missing={sorted(expected - actual)}, unexpected={sorted(actual - expected)}"
        )
    children = policies["max_children"]
    word = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight"}.get(children)
    if word is None:
        raise RenderError("max_children outside supported word mapping (1..8)")
    output: dict[Path, str] = {}
    for role in sorted(expected):
        source_path = agents_dir / f"{role}.toml"
        model, effort = role_model(models, role, "codex")
        body = replace_tokens(read_text(source_path), {"codex_model": model, "effort": effort}, source_path)
        body = prefix_toml_description(body, identities[role], source_path)
        output[root / ".codex" / "agents" / f"{role}.toml"] = f"# {GENERATED} Canonical Olympus role: olympus/roles/{role}.md.\n" + body

    root_source = adapter / "root.md"
    root_prompt = replace_tokens(read_text(root_source), {"max_children": children, "max_children_word": word}, root_source)
    _, remainder = root_prompt.split("\n", 1)
    root_title = f"# {identities['kael']}"
    output[root / "CODEX.md"] = f"{root_title}\n\n<!-- {GENERATED} Canonical Olympus role: olympus/roles/kael.md. -->\n{remainder}"

    config_path = adapter / "config.toml"
    kael_model, kael_effort = role_model(models, "kael", "codex")
    config = replace_tokens(
        read_text(config_path),
        {
            "codex_kael_model": kael_model,
            "kael_effort": kael_effort,
            "max_children": children,
        },
        config_path,
    )
    output[root / ".codex" / "config.toml"] = f"# {GENERATED}\n" + config
    return output


def capability_doc(capabilities: dict) -> str:
    lines = [
        "<!-- " + GENERATED + " Source: olympus/harnesses/capabilities.toml. -->",
        "# Olympus harness capability contract",
        "",
        "`SUPPORTED`, `ADAPTABLE`, `PARTIAL`, `GAP`, and `NOT_NEEDED` describe the Olympus guarantee available through each adapter. A GAP never weakens Core policy.",
        "",
        "| Capability | OpenCode | Codex |",
        "|---|---|---|",
    ]
    for capability in CAPABILITIES:
        lines.append(f"| `{capability}` | {capabilities['opencode'][capability]} | {capabilities['codex'][capability]} |")
    lines.extend(
        [
            "",
            "OpenCode provides native hard DENY, explicit `/maintain` → Aegis, and the Activity HUD. Codex currently uses adaptable/native ASK, reports DENY and Aegis as GAP, and relies on basic/partial native activity visibility. Do not infer stronger enforcement than these states claim.",
            "",
        ]
    )
    return "\n".join(lines)


def outputs_for(root: Path, selected: str) -> dict[Path, str]:
    models, policies, capabilities, identities, roles = checked_sources(root)
    output: dict[Path, str] = {}
    if selected in ("opencode", "all"):
        output.update(opencode_outputs(root, models, policies, identities, roles))
    if selected in ("codex", "all"):
        output.update(codex_outputs(root, models, policies, identities, roles))
    if selected == "all":
        output[root / "docs" / "HARNESS-CAPABILITIES.md"] = capability_doc(capabilities)
    return output


def run(root: Path, action: str, selected: str) -> int:
    output = outputs_for(root, selected)
    changes = []
    for path in sorted(output, key=lambda item: item.relative_to(root).as_posix().casefold()):
        rel = path.relative_to(root).as_posix()
        expected = output[path]
        exists = path.is_file()
        actual = read_text(path) if exists else None
        if actual != expected:
            changes.append((path, rel, "drift" if exists else "missing", expected))

    if action == "check":
        if changes:
            for _, rel, state, _ in changes:
                print(f"DRIFT {state}: {rel}")
            print(f"HARNESS_RENDER_CHECK: FAIL ({len(changes)} mismatch(es))")
            return 1
        print(f"HARNESS_RENDER_CHECK: PASS ({selected}; {len(output)} managed output(s); read-only)")
        return 0

    # All sources and expected content were validated before the first write.
    for path, _, _, expected in changes:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
    print(f"HARNESS_RENDER: PASS ({selected}; wrote {len(changes)} changed output(s), {len(output) - len(changes)} unchanged)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("render", "check"), help="render managed output or perform read-only drift check")
    parser.add_argument("--harness", choices=("opencode", "codex", "all"), default="all")
    parser.add_argument("--root", type=Path, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = (args.root or Path(__file__).resolve().parents[1]).resolve()
    try:
        return run(root, args.action, args.harness)
    except RenderError as error:
        print(f"HARNESS_RENDER: ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
